### ISSUE TITLE
Possible to customize emoji set?

### ISSUE THREAD

**Issue by fluffy-critter** [martymcguire/indiewebring.ws#8]
My webring entry got the rather hard to view and literally-impossible-to-type designation "🆑❇️*⃣". It'd be neat if we had the option to specify some (unique) emoji that are particularly relevant to us, for example if I had a choice I'd go with 💜🐝💜.

**Comment by martymcguire** [comment]
Thanks @fluffy-critter !! Sorry for the un-type-able emoji ID. :sweat_smile: 

To give some insight into the situation: these designations aren't randomly assigned, but are generated from a hash of the URL you sign in with. As unlikely as it might be, since I can't currently guarantee that someone won't sign up with a URL that hashes to :purple_heart::bee::purple_heart:, I can't assign it away.

This is by no means the first time that emoji IDs have turned out to be a... challenge. Since the initial launch of the site (when each site was hashed to a single emoji!) I have changed the hashing mechanism twice. Once when I [removed flags from the possible set of emojis](https://github.com/martymcguire/hash-emoji-without-borders) and once when I fixed a URL normalization issue. Since the hash scheme changes would have affected existing users, I bumped up the number of emoji in the generated hashes each time.

Long term, I would like to retire these emoji identifiers entirely, so I am shopping for a replacement, if you have suggestions.

Short term, well. you may have noticed I admitted above that no single- or double-emoji IDs will be generated going forward. :sweat_smile: In an extremely unsustainable and limited offering, I am willing to entertain requests for single- and double-emoji IDs for now. :shushing_face: :see_no_evil:

**Comment by fluffy-critter** [comment]
Well in that case could I be reassigned to 🐝💜? :)

**Comment by fluffy-critter** [comment]
Also, theoretically you'd still have to handle hash collisions even with three-emoji things. Wouldn't a pre-assigned emoji set just be a special case of a hash collision?

**Comment by martymcguire** [comment]
> Also, **_theoretically_** you'd still have to handle hash collisions even with three-emoji things.

Emphasis added. :joy:

There is [currently no checking for or handling of hash collisions](https://github.com/martymcguire/indiewebring.ws/blob/master/lib/models/site.js#L7).

I figure the hash space is sparse enough for non-malicious folks not to cause collisions before I fix it or move on to something else. I guess I have an internal hang-up about tempting fate through hand-picking??

Anyway the slug for `http://beesbuzz.biz/` is now :bee::purple_heart: !

Closing this issue before other folks ask. :joy:
